microsoft/fastlane-plugin-appcenter

- README.md
direct link to generation of api token instead of linking to docs that explain how to test the api via swagger (although it's nice this is possible!)
> Better API Token link

- README.md
- fastlane-plugin-appcenter.gemspec
- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- spec/spec_helper.rb
This add a Destination names parameter which can be used to submit builds automatically to a store.
Example:
```
appcenter_upload(
app_name: "AppName",
destination: "iTunes Connect users"
)
```
This will release every build to TestFlight.
> Adds Destination parameter

- .rubocop.yml
Currently there is  a TravisCI build error:
```
Error: The `Style/MethodMissing` cop has been split into `Style/MethodMissingSuper` and `Style/MissingRespondToMissing`.
(obsolete configuration found in .rubocop.yml, please update it)
```
This replaces `Style/MethodMissing` with both `Style/MethodMissingSuper` and `Style/MissingRespondToMissing` to fix it.
> Fix obsolete configuration found in .rubocop.yml

- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
Running `fastlane action appcenter_upload` to print the documentation of the plugin/action crashes fastlane, because `self.details` is supposed to be a `String`, not an `Array`.
This commit fixes `self.details` to return a string instead of an array, which will prevent `fastlane action` to crash.
> Fix crash when printing doc

- fastlane/Fastfile
- lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
- spec/appcenter_upload_spec.rb
Fixes error for groups with spaces in name:
```
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/home/circleci/.rubies/ruby-2.4.3/bin/fastlane)
URI::InvalidURIError: [!] bad URI(is not URI?): /v0.1/apps<...>
```
> Escape group names

- README.md
- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
It was unclear to some people that this param became available and the default changed to `false`
> Improved docs for notify-testers

- .rubocop.yml
Saw error when running RuboCop
```
Running RuboCop...
Error: The `Layout/IndentHash` cop has been renamed to `Layout/IndentFirstHashElement`.
(obsolete configuration found in .rubocop.yml, please update it)
RuboCop failed!
```
> Fix error from RuboCop

- .rubocop.yml
- fastlane/Fastfile
Your example `Fastfile` that's linked to from the README shows a `release_notes_clipping` option. When I run it with that option enabled I get the following error:
```
Could not find option 'release_notes_clipping' in the list of available options: api_token, 
owner_name, app_name, apk, ipa, dsym, upload_dsym_only, group, mandatory_update,
notify_testers, release_notes, should_clip, release_notes_link
```
I assume that the `should_clip` option is the correct one.
Updated the `Fastfile` to use `should_clip` instead
> Replace release_notes_clipping with should_clip in example file

- fastlane/Fastfile
- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- spec/appcenter_upload_spec.rb
First step of address #64 
1. Support `destinations` and `destination_type` as the inputs. Both are optional and default to `Collaborators` distribution group.
2. Only `group` is supported as `destination_type`. Support for others will be added in future PRs.
3. Deprecate `group` input. Throws error when it is used.
> Refactor to support destination type, in preparation of supporting distributing to store

- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
- lib/fastlane/plugin/appcenter/version.rb
- spec/appcenter_upload_spec.rb
Before, the lane would have just swallowed this error. It would have printed it, but still treated the call as a success.
Now, it will fail execution on a service error, i.e. when this is caused by a service outage, to signal the lane did not succeed.
This should fix wrong treatment as mentioned in #89 
Added this behavior only to the case where initial creation of the release failed and when updating the release upload to completed failed.
For cases where symbol or mapping upload fail we typically don't want to fail the entire upload, as by then the release would have been created and re-uploading might cause another release, while retroactively uploading symbols or mappings can be done independently.
> Fail action on release creation/upload exceptions

- README.md
- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
- lib/fastlane/plugin/appcenter/version.rb
- spec/appcenter_upload_spec.rb
This adds support for Android App Bundle (AAB files) to the stores upload logic.
> Implement support for AAB upload to store

- lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
Add the ability to set the upload url from the environment. Useful when developing against a non-production setup. 
Requires re-syntaxing of the faraday requests. They were all written as e.g.
```ruby
connection.post do |req|
req.url("/path/to/endpoint")
...
end
```
Now they are like so:
```ruby
connection.post("path/to/endpoint") do |req|
...
end
```
(note lack of leading slash). This makes it possible to support setting a base url that includes a path at the end (using `req.url(...)` overwrites the path).
> Allow base url to be set by environment

- README.md
When I tried to upload an ipa file to the app center I accidentally used the `name` instead of the `username`. 
This leads to the following error message:
`Error getting app some/App, 403: {"message"=>"Forbidden", "statusCode"=>403, "code"=>"Forbidden"}`
I had to contact the support to solve this problem.
I adjusted the readme file to specify which name the user should use because there are two different user variables for an account.
> Improve owner_name description

- README.md
- fastlane/Fastfile
- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
- spec/appcenter_upload_spec.rb
* Added optional parameter `owner_type` with values `user` and `organization`, default - `user`
> Support auto-creating apps in App Center organization

- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
It contains secret tokens, and should not be printed out to logs that
may be stored in a CI/CD environment. Rather than obfuscating the
tokens and render an invalid URL, let's just not print the download
URL at all.
> Do not log public download URL

- README.md
- fastlane/fetch_devices/Fastfile
- lib/fastlane/plugin/appcenter/actions/appcenter_fetch_devices_action.rb
- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
- spec/appcenter_fetch_devices_action_spec.rb
This builds up on the work done in #123 which adds the new action 'appcenter_fetch_devices', but adds a new `destination` key, which I believe will allow for better integration with the `appcenter_upload` action, as well as allowing users with a lot of devices to be have more control over which ones to register.
> appcenter_fetch_devices: Add 'destinations' key and some error handling

- spec/appcenter_upload_spec.rb
> Address warning when running tests

- README.md
I've wasted about 1.5 hrs trying different things due to poor error messages on the api when I submit an app to appcenter using this plugin, I'm using an organisation now - previously a user owner_type. so it worked. It wasn't until I searched the issues for this error: `App with name <app_name> not found, create one?` 
Ideally the api should say something useful. or just resolve to an app in an org...
anyway hopefully this updated readme.md will save some people time in the future! maybe force owner_type to be mandatory?
> show usage of owner_type

- README.md
- fastlane-plugin-appcenter.gemspec
... as `lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]` has been introduced in this version, which is required by `appcenter_upload_action`. Using `appcenter_upload_action` with an older version of fastlane produces the error: ` uninitialized constant Fastlane::Actions::SharedValues::GRADLE_AAB_OUTPUT_PATH`
> correct-fastlane-dependency: updates minimum fastlane version to 2.96.0

- lib/fastlane/plugin/appcenter/version.rb
Here's a new release of the App Center fastlane plugin!
This adds support for:
- All known platform and file extensions for upload (see #136)
- Integration with Azure Pipelines with nicely integrated JUnit test results
- `strict` mode which will fail early an upload if the plugin detects an inconsistency
This also deprecates (but does not break support) for:
- `apk:`, `aab:`, `ipa:` fields. They've all been superseded by `file:`.
> Release 1.6.0

- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- spec/appcenter_upload_spec.rb
Related to: https://github.com/microsoft/fastlane-plugin-appcenter/issues/154
Hi 👋 , took a while to track this one down.
The effect of this bug is not seeing install buttons in Microsoft App Center when released via fastlane but visible when manually creating release via web UI.
We build 2 packages in the one lane for distribution - one via Microsoft App Center (was Hockey) and the other via testflight - 2 streams and 2 different targets.
The first build we send to MS App Center, but only _after_ building the second release, then packaging both with github PRs etc. 
The `ipa` option is deprecated on `appcenter_upload` commands so we use `file`. However there is a mismatch of using `.detect` on the parameters given as that is choosing the _default_ `IPA_OUTPUT_PATH` which has been set by …
> Fix: Priority of deprecated fields and file parameter

- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- spec/appcenter_upload_spec.rb
Handling platforms check properly.
Since we verify if the app_platform is provided, if not we prompt the user to select from our `platforms` mapping.
And while doing so, there is an error where we pass platforms[os] instead it should be platforms[os.to_sym]
> Fixing the app creation by handling os correctly

- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- spec/appcenter_upload_spec.rb
As part of the config key :file, we are checking the supported file extensions based on environment variable `SharedValues::PLATFORM_NAME`.
And if this is not present, we are showing incorrect error message.
`[19:34:18]: Unknown platform '', consider using one of: [:android, :ios, :mac, :windows, :custom]`
This is slightly confusing when users are using this for only upload action and doesn't want to set the platform.
When user gives AppName with spaces/special characters, then url construction for GET is failing with **URI::InvalidURIError: [!] bad URI(is not URI?): v0.1/apps/korea/test app**
If we do URI.encode this error is resolved but fails in app_creation steps with validation errors.
Hence handling this just by rescue-ing on URI::InvalidURIError.
> Fixing the platform warning and  bad URI(is not URI?) error

- README.md
- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- spec/appcenter_upload_spec.rb
This is to support few feature requests where customers just want to upload the builds but not symbols.
Hence introduced a new flag called `upload_build_only` 
And when set to true, this will upload build only and skips symbols/mapping
> Adding support to upload_build_only option

- lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
See comment on #136. Only `.app.zip` is specially handled in App Center, no need to have generic code for `.ext.zip`.
> Special case .app.zip extension utility

- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- spec/appcenter_upload_spec.rb
As part of this plugin, we support when app doesn't exists, we have an option to create.
And when we don't provide app_platform, we prompt the users to select from supported platforms.
But this was not supported in Windows case.
Added support to this.
> Adding windows support for app creation when not exists

- .rubocop.yml
- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- spec/appcenter_upload_spec.rb
Distributing build to all distribution groups by using the '*' as destination. Make exceptions by adding distributions groups to destination_excludes
> Adding support for * as destinations

- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- spec/appcenter_upload_spec.rb
uses lane_context[SharedValues:: GRADLE_MAPPING_TXT_OUTPUT_PATH] from gradle plugin to set a default value for mapping.
> use lane_context for android mapping text

- .rubocop.yml
- lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
For the upload action, this adds full traces of the API calls: URL, body and response contents. Enable this using `export DEBUG=1`.
Also, this fixes invalid calls to inexistent method `UI.crash!`.
Finally, testing by App Center devs is easier by using `APPCENTER_ENV=int` rather than having to set the URL manually. The base URL can also be found in the CLI source code.
> Add debug logs for all API calls (upload action)

- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
While unconventional, we can use fastlane plugin to drive the creation of apps and uploads to non-ios, non-android platforms.
Fixes #207
Fixes #205
> Add missing platforms

- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- spec/appcenter_upload_spec.rb
Hello,
I've found little issue with uploading of the notarized macOS app. I tried to run `appcenter_upload` with notarized _.app_ file, but when I downloaded the uploaded app, the app wasn't notarized.
I've found that the issue is with compressing of the app, which is a part of the `appcenter_upload` action. When the app is compressed without symlinks, it will break notarization of the app. So _.app_ from created _.zip_ file is no longer notarized.
This little adjustment of the `ZipAction` usage resolve that issue.
It fix #214 issue.
> Fix appcenter_upload breaks the notarization of the macOS app #214

- README.md
- lib/fastlane/plugin/appcenter/version.rb
Changes:
- Fixes upload of macOS notarized apps
- Add newly created apps to distribution groups
- Fixes running of individual rspecs
- Improves debug
> Version 1.8.1

- README.md
- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
- lib/fastlane/plugin/appcenter/version.rb
* Use the current appcenter upload endpoint to distribute releases.
* Large release file upload is now split into 4MB chunks (or larger, determined by server response).
* Each chunk has 2 retries.
* Clarify the timeout request parameter behavior in the documentation.
> Version 1.9.0

- lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
After updating fastlane to 2.161.0 or later, there is a failure when uploading builds using this plugin. The issue appears to be caused by [this change](https://github.com/fastlane/fastlane/commit/7a6b9d684b09c71279daf3471a44bce53a020a53) which altered default behavior for `Content-Type` on requests by any gem loaded by fastlane. As a result, this upload request is now issued with `application/www-x-form-urlencoded` instead of having no `Content-Type` header. Specifying a desired header fixes this issue, though I'm not sure if `application/octet-stream` is correct for this request.
The error seen currently is:
```
Client error: 400: {"error"=>{"code"=>400, "message"=>"The request contains invalid content."}}
```
Fixes #247 and #246
> Specify content-type on chunk upload api since the default is not supported

- README.md
- lib/fastlane/plugin/appcenter/actions/appcenter_codepush_release_react.rb
CodePush is part of AppCenter
This Pull request adds support for deploying updates via CodePush for React Native apps
For usage it also requires installation of AppCenter CLI
All necessary options for `appcenter codepush` CLI command are supported
Updated README with description of action's options and small usage example
> Add CodePush release-react action

- fastlane/Fastfile
Fixes `test_macos`, `test_macos_sparkle` lanes. To reproduce run 
```
cd fastlane
fastlane test_macos
fastlane test_macos_sparkle
```
Error:
```
fastlane-plugin-appcenter/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:312:in `get_or_create_app': \e[31m[!] undefined method `length' for nil:NilClass\e[0m (NoMethodError)
```
> Fix macOS tests

- lib/fastlane/plugin/appcenter/actions/appcenter_codepush_release_react.rb
- spec/appcenter_codepush_release_react_spec.rb
This PR adds a `use_local_appcenter_cli` option to the `appcenter_codepush_release_react` action. When the option is set to `true` the action will use the locally installed appcenter cli.
This means users of the appcenter plugin can install the appcenter cli with the rest of their node modules. This allows for better package hygiene in the CI and development environment.
> Add support for local appcenter cli executable when codepushing

- lib/fastlane/plugin/appcenter/actions/appcenter_codepush_release_react.rb
If your project uses some different names for the xcode-project-file and plist-file it is now possible to use codepush
> Allow xcode-project-file and info-plist params for codepush

- lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
This PR fixes a misleading ruby error caused by parsing a non-array object received from backend.
[AB#102654](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/102654)
#322
> Make sure app_distribution_groups is an array before accessing it

- lib/fastlane/plugin/appcenter/actions/appcenter_codepush_release_react.rb
Prevent npm from parsing arguments. Without this, devs cannot use local cli.
https://docs.npmjs.com/cli/v7/commands/npm-exec#npx-vs-npm-exec
> fix(local cli): prevent npm from parsing arguments

- README.md
- lib/fastlane/plugin/appcenter/actions/appcenter_codepush_release_react.rb
- spec/appcenter_codepush_release_react_spec.rb
Add codepush support for the appcenter-cli extra bundler options
Resolves #312
> Add codepush support for extra bundler options

- fastlane-plugin-appcenter.gemspec
Adds csv dependency as it was removed from default gems starting from Ruby 3.4.0.
[AB#104379] (https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/104379)
https://github.com/microsoft/fastlane-plugin-appcenter/issues/338/
> Add csv explicitly dependency as it was removed in 3.4.0
