lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb, lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
=> Move shared values definition from module Fastlane::Helper to Fastlane::Actions

fastlane/Fastfile, fastlane/mapping.txt, lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb, lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
=> fix upload android mapping.txt

README.md
=> Update readme for new parameters supporting store distribution

README.md, fastlane/Fastfile, lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb, lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb, spec/appcenter_upload_spec.rb
Adds official mapping support.
Warns that unofficial mapping support is being deprecated.
Renames internal functions for symbol_upload to be more generic.
=> Add android mapping support

lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
Receiving error `NameError: [!] undefined local variable or method `owner' for FastlaneCore::Helper::AppcenterHelper:Class` on upload. I believe this should fix it.
=> fix undefined local variable or method `owner'

README.md, lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb, lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb
closes https://github.com/microsoft/fastlane-plugin-appcenter/issues/31
=> Add timeout option for uploading large builds

lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
=> Fix typo in appcenter_upload_action.rb

README.md, generate_docs.sh, lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
The table was generated with
fastlane action appcenter_upload
And then manually stylized.
=> Clarify docs & README

lib/fastlane/plugin/appcenter/version.rb
Changes:
- Added new action `appcenter_fetch_devices` (many thanks to @benkane)
- Added support for dsa_signature to support Sparkle update feeds
- Improved documentation and logs
=> Release version 1.5.0

lib/fastlane/plugin/appcenter/version.rb
Bumping the release version from 1.6.0 to 1.7.0
=> Release 1.7.0

fastlane/Fastfile
=> Use `file:` in example Fastfile

lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb, spec/appcenter_upload_spec.rb
=> Allow dsym: for all Apple builds

README.md
Updating Readme in regards to customer support since we're moving away from the bubble-chat style of interaction to email-based interaction.
=> Move to web-based ticketing system from the bubble-chat style

lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
Hi I just want to add this in the description so consumers can easily know the exact strings without checking the code. Let me know what you think!
=> Add description on possible values for app_os

lib/fastlane/plugin/appcenter/version.rb
Minor update for new functionality #250
=> Version to 1.11.0

.rubocop.yml, spec/appcenter_upload_spec.rb
Get RuboCop running, and passing.
=> Rubocop config update & fixes

lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb, spec/appcenter_fetch_devices_action_spec.rb, spec/appcenter_fetch_version_number_spec.rb, spec/appcenter_stub.rb, spec/appcenter_upload_spec.rb, spec/fetch_version_number_stubs.rb, spec/upload_stubs.rb
**Related work item:** [link](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/Peter-Team/Features/?workitem=84317).
**Description:**
AppCenter backend sometimes returns 429 error. We have to add retrying for this error to prevent the plugin from stopping his work.
**Done:**
1) Added retrying logic into all AppcenterHelper methods.
2) Added some rspec tests.
=> Add retrying 429 error and Faraday exception.

lib/fastlane/plugin/appcenter/version.rb
Release 1.11.1.
Related feature: [link](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/Peter-Team/Features/?workitem=84317).
=> incremented version

README.md, lib/fastlane/plugin/appcenter/actions/appcenter_codepush_release_react.rb
Add support for [private-key-path](https://microsoft.github.io/code-push/articles/CodeSigningAnnouncement.html) parameter for codepush actions :v:
=> Add support for private-key-path parameter

lib/fastlane/plugin/appcenter/actions/appcenter_codepush_release_react.rb, spec/appcenter_codepush_release_react_spec.rb
I see that the appcenter codepush cli currently support hermes on codepush. So I make this PR to add this parameter on fastlane function. 
Please review and let me know if need to improve
=> [Add] support hermes in code push

lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb
Fix issue mentioned here -> https://github.com/microsoft/fastlane-plugin-appcenter/issues/320 to clarify the message
=> Update error handling to address possible invalid owner_name

README.md
Noticed a random quotation mark character in the README…
=> Remove hanging quotation mark in README

.azurepipelines/build-fastlane-plugin-1es.yml
Migrating Pipelines to 1ES Template. 
[AB#104414](https://dev.azure.com/msmobilecenter/Mobile-Center/_boards/board/t/Mobile%20SDK%20team/Backlog%20Items/?workitem=104414)
Successful build: https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1520903&view=results
=> [Pipelines] Migrate to 1ES pipeline
